name: flutter_application_7
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'
dependencies:
  awesome_dialog: ^3.0.2
  cloud_firestore: ^4.5.2
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  intl: ^0.17.0
  lottie: ^2.3.2
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  syncfusion_flutter_charts: ^21.1.41
  syncfusion_flutter_sliders: ^21.1.41
  table_calendar: ^3.0.9
dependency_overrides:
  intl: ^0.18.0

dev_dependencies:

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
